# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc21cc56ee18c9addc73e4d7a68314362e53613528dba3e6182008ff0c41bd2b9ebae17571c394e804a7bf32ff0bbec7137f2dea71b9a16ca25ec5242b4e17a5

test:
  secret_key_base: d41496f257e44b079431032416ae42c5d416dc536b456f43fcea322d95f69ea6663158a6ff86ad4ee132edc05bd1207f4c6d8fc8531b369c1588cbd548bd9a54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
